[project]
name = "chomp"
version = "1.1.0"
description = "Lightweight, multimodal ingester, start collecting web2/3 data in minutes"
authors = [
    {name = "JakeTheSlug", email = "jake@astrolab.fi"},
]
readme = "README.md"
license = {text = "MIT"}
requires-python = "==3.11.*"

dependencies = [
    "redis==5.2.0",
    "python-dotenv==1.0.1",
    "pyyaml>=6.0.2",
    "yamale==5.2.1",
    "aiocron==1.8",
    "aiohttp>=3.11.7",
    "fastapi>=0.115.5",
    "uvicorn[standard]>=0.32.1",
    "beautifulsoup4>=4.12.3",
    "lxml>=5.3.0",
    "web3==6.20.3",
    "multicall==0.9.0",
    "taospy==2.7.16",
    "orjson>=3.10.3",
    "numpy>=1.26.4",
    "playwright>=1.49.0",
    "python-dateutil>=2.9.0",
    # "asyncpg>=0.29.0",
    # "pymongo>=4.7.2",
    # "opentsdb-py>=0.6.0",
    # "solana>=0.36.2",
    # "solders>=0.23.0"
    "httpx>=0.28.1",
    "tomli>=2.2.1",
    "polars>=1.21.0",
    "pyarrow>=19.0.0",
]
